const scales = [
	{
		id: 1,
		name: 'A',
		notes: {
			root: 'A',
			minorSecond: 'A#/Bb',
			majorSecond: 'B',
			minorThird: 'C',
			majorThird: 'C#/Db',
			dimForth: 'C#/Db',
			perfForth: 'D',
			augForth: 'D#/Eb',
			dimFifth: 'D#/Eb',
			perfFifth: 'E',
			augFifth: 'F',
			minorSixth: 'F',
			majorSixth: 'F#/Gb',
			minorSeventh: 'G',
			majorSeventh: 'G#/Ab',
			octave: 'A',
		},
	},
	{
		id: 2,
		name: 'A#/Bb',
		notes: {
			root: 'A#/Bb',
			minorSecond: 'B',
			majorSecond: 'C',
			minorThird: 'C#/Db',
			majorThird: 'D',
			dimForth: 'D',
			perfForth: 'D#/Eb',
			augForth: 'E',
			dimFifth: 'E',
			perfFifth: 'F',
			augFifth: 'F#/Gb',
			minorSixth: 'F#/Gb',
			majorSixth: 'G',
			minorSeventh: 'G#/Ab',
			majorSeventh: 'A',
			octave: 'A#/Bb',
		},
	},
	{
		id: 3,
		name: 'B',
		notes: {
			root: 'B',
			minorSecond: 'C',
			majorSecond: 'C#/Db',
			minorThird: 'D',
			majorThird: 'D#/Eb',
			dimForth: 'D#/Eb',
			perfForth: 'E',
			augForth: 'F',
			dimFifth: 'F',
			perfFifth: 'F#/Gb',
			augFifth: 'G',
			minorSixth: 'G',
			majorSixth: 'G#/Ab',
			minorSeventh: 'A',
			majorSeventh: 'A#/Bb',
			octave: 'B',
		},
	},
	{
		id: 4,
		name: 'C',
		notes: {
			root: 'C',
			minorSecond: 'C#/Db',
			majorSecond: 'D',
			minorThird: 'D#/Eb',
			majorThird: 'E',
			dimForth: 'E',
			perfForth: 'F',
			augForth: 'F#/Gb',
			dimFifth: 'F#/Gb',
			perfFifth: 'G',
			augFifth: 'G#/Ab',
			minorSixth: 'G#/Ab',
			majorSixth: 'A',
			minorSeventh: 'A#/Bb',
			majorSeventh: 'B',
			octave: 'C',
		},
	},
	{
		id: 5,
		name: 'C#/Db',
		notes: {
			root: 'C#/Db',
			minorSecond: 'D',
			majorSecond: 'D#/Eb',
			minorThird: 'E',
			majorThird: 'F',
			dimForth: 'F',
			perfForth: 'F#/Gb',
			augForth: 'G',
			dimFifth: 'G',
			perfFifth: 'G#/Ab',
			augFifth: 'A',
			minorSixth: 'A',
			majorSixth: 'A#/Bb',
			minorSeventh: 'B',
			majorSeventh: 'C',
			octave: 'C#/Db',
		},
	},
	{
		id: 6,
		name: 'D',
		notes: {
			root: 'D',
			minorSecond: 'D#/Eb',
			majorSecond: 'E',
			minorThird: 'F',
			majorThird: 'F#/Gb',
			dimForth: 'F#/Gb',
			perfForth: 'G',
			augForth: 'G#/Ab',
			dimFifth: 'G#/Ab',
			perfFifth: 'A',
			augFifth: 'A#/Bb',
			minorSixth: 'A#/Bb',
			majorSixth: 'B',
			minorSeventh: 'C',
			majorSeventh: 'C#/Db',
			octave: 'D',
		},
	},
	{
		id: 7,
		name: 'D#/Eb',
		notes: {
			root: 'D#/Eb',
			minorSecond: 'E',
			majorSecond: 'F',
			minorThird: 'F#/Gb',
			majorThird: 'G',
			dimForth: 'G',
			perfForth: 'G#/Ab',
			augForth: 'A',
			dimFifth: 'A',
			perfFifth: 'A#/Bb',
			augFifth: 'B',
			minorSixth: 'B',
			majorSixth: 'C',
			minorSeventh: 'C#/Db',
			majorSeventh: 'D',
			octave: 'D#/Eb',
		},
	},
	{
		id: 8,
		name: 'E',
		notes: {
			root: 'E',
			minorSecond: 'F',
			majorSecond: 'F#/Gb',
			minorThird: 'G',
			majorThird: 'G#/Ab',
			dimForth: 'G#/Ab',
			perfForth: 'A',
			augForth: 'A#/Bb',
			dimFifth: 'A#/Bb',
			perfFifth: 'B',
			augFifth: 'C',
			minorSixth: 'C',
			majorSixth: 'C#/Db',
			minorSeventh: 'D',
			majorSeventh: 'D#/Eb',
			octave: 'E',
		},
	},
	{
		id: 9,
		name: 'F',
		notes: {
			root: 'F',
			minorSecond: 'F#/Gb',
			majorSecond: 'G',
			minorThird: 'G#/Ab',
			majorThird: 'A',
			dimForth: 'A',
			perfForth: 'A#/Bb',
			augForth: 'B',
			dimFifth: 'B',
			perfFifth: 'C',
			augFifth: 'C#/Db',
			minorSixth: 'C#/Db',
			majorSixth: 'D',
			minorSeventh: 'D#/Eb',
			majorSeventh: 'E',
			octave: 'F',
		},
	},
	{
		id: 10,
		name: 'F#/Gb',
		notes: {
			root: 'F#/Gb',
			minorSecond: 'G',
			majorSecond: 'G#/Ab',
			minorThird: 'A',
			majorThird: 'A#/Bb',
			dimForth: 'A#/Bb',
			perfForth: 'B',
			augForth: 'C',
			dimFifth: 'C',
			perfFifth: 'C#/Db',
			augFifth: 'D',
			minorSixth: 'D',
			majorSixth: 'D#/Eb',
			minorSeventh: 'E',
			majorSeventh: 'F',
			octave: 'F#/Gb',
		},
	},
	{
		id: 11,
		name: 'G',
		notes: {
			root: 'G',
			minorSecond: 'G#/Ab',
			majorSecond: 'A',
			minorThird: 'A#/Bb',
			majorThird: 'B',
			dimForth: 'B',
			perfForth: 'C',
			augForth: 'C#/Db',
			dimFifth: 'C#/Db',
			perfFifth: 'D',
			augFifth: 'D#/Eb',
			minorSixth: 'D#/Eb',
			majorSixth: 'E',
			minorSeventh: 'F',
			majorSeventh: 'F#/Gb',
			octave: 'G',
		},
	},
	{
		id: 12,
		name: 'G#/Ab',
		notes: {
			root: 'G#/Ab',
			minorSecond: 'A',
			majorSecond: 'A#/Bb',
			minorThird: 'B',
			majorThird: 'C',
			dimForth: 'C',
			perfForth: 'C#/Db',
			augForth: 'D',
			dimFifth: 'D',
			perfFifth: 'D#/Eb',
			augFifth: 'E',
			minorSixth: 'E',
			majorSixth: 'F',
			minorSeventh: 'F#/Gb',
			majorSeventh: 'G',
			octave: 'G#/Ab',
		},
	},
];

export default scales;
